---
# defaults file for import_export
aap_configuration_async_delay: 5
aap_configuration_async_retries: 60
aap_configuration_secure_logging: false
aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'AAP_HOST')) }}"
aap_validate_certs: "{{ vault_aap_validate_certs | default(lookup('env', 'AAP_VERIFY_SSL')) }}"
...
