---
- name: Import/Export AAP
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Assert import_export_mode is set
      ansible.builtin.assert:
        that:
          - import_export_mode is defined
        fail_msg: "import_export_mode is required"
      tags:
        - always

  roles:
    - role: import_export
...
