---
galaxy_info:
  author: Lenny Shirley II
  description: Converts a flat directory of Ansible variable files (e.g., from an AAP export) into a structured file tree.
  company: Red Hat
  issue_tracker_url: https://github.com/lennysh/aap-casc-demo/issues
  license: MIT
  min_ansible_version: 2.16.0
  galaxy_tags: []
dependencies: []
