---
galaxy_info:
  author: Lenny Shirley II
  description: Import/Export AAP Configuration as Code (CasC)
  company: Red Hat
  issue_tracker_url: https://github.com/lennysh/aap-casc-demo/issues
  license: MIT
  min_ansible_version: 2.16.0
  galaxy_tags: []
dependencies: []
